version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    volumes:
      - ./:/usr/nodeapp
    environment:
      - NODE_ENV=production
    command: npm start