version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/usr/nodeapp
      
    environment:
      - NODE_ENV=development
    command: npm run dev
